/*
 * @Description:
 * @Autor: Ming
 * @LastEditors: Ming
 * @LastEditTime: 2023-01-12 16:46:35
 */
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v2"
)

var conf AutoGenerated

func init() {
	yamlFile, err := os.ReadFile("conf.yaml")
	if err != nil {
		fmt.Println(err.Error())
		panic("配置文件读取错误！")
	}
	err = yaml.Unmarshal(yamlFile, &conf)
	if err != nil {
		fmt.Println(err.Error())
		panic("配置文件解析错误！")
	}
	fmt.Println("配置文件读取成功")
}

func GetConf() AutoGenerated {
	return conf
}
